site_name: djismgaming's tech home
site_url: https://djismgaming.github.io
repo_url: http://www.github.com/djismgaming/djismgaming.github.io
repo_name: djismgaming.github.io
edit_uri: edit/main/docs/
site_description: Web home for tech things!
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    # - navigation.sections
    # - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: en
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: purple
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: purple

plugins:
  - search
  - blog:
      post_excerpt: required
      post_excerpt_max_authors: 0
      post_excerpt_separator: <!-- more -->
      archive: false
      categories: false
  - social
  - tags
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/djismgaming
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/djismgaming
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/djismgaming
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ismaellm/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: ⚓︎
      permalink_title: Anchor link to this section for reference

copyright: |
  &copy; 2023 - 2024 <a href="https://github.com/djismgaming"  target="_blank" rel="noopener">Ismael Lamberty</a>