site_name: djismgaming's tech home
site_url: https://djismgaming.github.io
site_description: Web home for tech things!
nav:
  - Home: index.md
  - About: about.md
theme: material
site_dir: ../djismgaming.github.io
